# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..file_utils import requires_sentencepiece


class AlbertTokenizer:

    @classmethod


class BarthezTokenizer:

    @classmethod


class BertGenerationTokenizer:

    @classmethod


class CamembertTokenizer:

    @classmethod


class MarianTokenizer:

    @classmethod


class MBartTokenizer:

    @classmethod


class MT5Tokenizer:

    @classmethod


class PegasusTokenizer:

    @classmethod


class ReformerTokenizer:

    @classmethod


class T5Tokenizer:

    @classmethod


class XLMProphetNetTokenizer:

    @classmethod


class XLMRobertaTokenizer:

    @classmethod


class XLNetTokenizer:

    @classmethod