# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..file_utils import requires_flax


FLAX_MODEL_MAPPING = None


class FlaxAutoModel:

    @classmethod


class FlaxBertModel:

    @classmethod


class FlaxRobertaModel:

    @classmethod