# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class FlaxControlNetModel(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxModelMixin(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxUNet2DConditionModel(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxAutoencoderKL(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxDiffusionPipeline(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxDDIMScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxDDPMScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxDPMSolverMultistepScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxEulerDiscreteScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxKarrasVeScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxLMSDiscreteScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxPNDMScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxSchedulerMixin(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod


class FlaxScoreSdeVeScheduler(metaclass=DummyObject):
    _backends = ["flax"]


    @classmethod

    @classmethod