# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class AltDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AltDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AmusedImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AmusedInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AmusedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AnimateDiffPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AnimateDiffSDXLPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AnimateDiffVideoToVideoPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AudioLDM2Pipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AudioLDM2ProjectionModel(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AudioLDM2UNet2DConditionModel(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AudioLDMPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class CLIPImageProjection(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class CycleDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class I2VGenXLPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFImg2ImgSuperResolutionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFInpaintingPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFInpaintingSuperResolutionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class IFSuperResolutionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class ImageTextPipelineOutput(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class Kandinsky3Img2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class Kandinsky3Pipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyImg2ImgCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyInpaintCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyPriorPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22CombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22ControlnetImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22ControlnetPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22Img2ImgCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22Img2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22InpaintCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22InpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22Pipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22PriorEmb2EmbPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class KandinskyV22PriorPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LatentConsistencyModelImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LatentConsistencyModelPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LDMTextToImagePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LEditsPPPipelineStableDiffusion(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LEditsPPPipelineStableDiffusionXL(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class MusicLDMPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class PaintByExamplePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class PIAPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class PixArtAlphaPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class PixArtSigmaPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class SemanticStableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class ShapEImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class ShapEPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableCascadeCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableCascadeDecoderPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableCascadePriorPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionAdapterPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionAttendAndExcitePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionControlNetImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionControlNetInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionControlNetPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionControlNetXSPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionDepth2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionDiffEditPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionGLIGENPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionGLIGENTextImagePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInpaintPipelineLegacy(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInstructPix2PixPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionLatentUpscalePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionLDM3DPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionModelEditingPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPanoramaPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionParadigmsPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPipelineSafe(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPix2PixZeroPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionSAGPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionUpscalePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLAdapterPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLControlNetImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLControlNetInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLControlNetPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLControlNetXSPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLInstructPix2PixPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionXLPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableUnCLIPImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableUnCLIPPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableVideoDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class TextToVideoSDPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class TextToVideoZeroPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class TextToVideoZeroSDXLPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UnCLIPImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UnCLIPPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UniDiffuserModel(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UniDiffuserPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UniDiffuserTextDecoder(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionDualGuidedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionTextToImagePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VideoToVideoSDPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VQDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class WuerstchenCombinedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class WuerstchenDecoderPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class WuerstchenPriorPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod