# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class SpectrogramDiffusionPipeline(metaclass=DummyObject):
    _backends = ["transformers", "torch", "note_seq"]


    @classmethod

    @classmethod