# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class TextualInversionLoaderMixin(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AltDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AltDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class AudioLDMPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class CycleDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class LDMTextToImagePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class PaintByExamplePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class SemanticStableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionAttendAndExcitePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionControlNetPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionDepth2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInpaintPipelineLegacy(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionInstructPix2PixPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionLatentUpscalePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionModelEditingPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPanoramaPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPipelineSafe(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionPix2PixZeroPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionSAGPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableDiffusionUpscalePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableUnCLIPImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class StableUnCLIPPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class TextToVideoSDPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UnCLIPImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class UnCLIPPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionDualGuidedPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionImageVariationPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VersatileDiffusionTextToImagePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod


class VQDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers"]


    @classmethod

    @classmethod