# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class OnnxRuntimeModel(metaclass=DummyObject):
    _backends = ["onnx"]


    @classmethod

    @classmethod