def run(self):
    entries = '\n'.join([f'    "{k}": "{v}",' for k, v in deps.items()])
    content = ['# THIS FILE HAS BEEN AUTOGENERATED. To update:',
        '# 1. modify the `_deps` dict in setup.py',
        '# 2. run `make deps_table_update`', 'deps = {', entries, '}', '']
    target = 'src/diffusers/dependency_versions_table.py'
    print(f'updating {target}')
    with open(target, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(content))
