def test_update(self):
    sot = SingleObjectTracker()
    sot.update(detection=det0)
    self.assertEqual(sot.box, det0.box)
    self.assertEqual(sot.score, det0.score)
    self.assertEqual(sot.class_id, det0.class_id)
    self.assertEqual(sot.feature, det0.feature)
    sot.update(detection=det1)
    self.assertEqual(sot.box, det1.box)
    self.assertEqual(sot.score, det1.score)
    self.assertEqual(sot.class_id, det1.class_id)
    self.assertEqual(sot.feature, det1.feature)
    sot.update(detection=None)
    self.assertEqual(sot.box, det1.box)
    self.assertEqual(sot.score, det1.score)
    self.assertEqual(sot.class_id, det1.class_id)
    self.assertEqual(sot.feature, det1.feature)
    self.assertEqual(sot.steps_positive, 2)
    self.assertEqual(sot.steps_alive, 3)
