def forward(self, x):
    nvtx.range_push('layer:conv1_x')
    x = self.conv1(x)
    x = self.bn1(x)
    x = self.relu(x)
    x = self.maxpool(x)
    nvtx.range_pop()
    nvtx.range_push('layer:conv2_x')
    x = self.layer1(x)
    nvtx.range_pop()
    nvtx.range_push('layer:conv3_x')
    x = self.layer2(x)
    nvtx.range_pop()
    nvtx.range_push('layer:conv4_x')
    x = self.layer3(x)
    nvtx.range_pop()
    nvtx.range_push('layer:conv5_x')
    x = self.layer4(x)
    nvtx.range_pop()
    x = self.avgpool(x)
    x = torch.flatten(x, 1)
    nvtx.range_push('layer:FC')
    x = self.fc(x)
    nvtx.range_pop()
    return x
