@torch.no_grad()
@replace_example_docstring(INPAINT_EXAMPLE_DOC_STRING)
def __call__(self, prompt: Union[str, List[str]], image: Union[torch.Tensor,
    PIL.Image.Image, List[torch.Tensor], List[PIL.Image.Image]], mask_image:
    Union[torch.Tensor, PIL.Image.Image, List[torch.Tensor], List[PIL.Image
    .Image]], negative_prompt: Optional[Union[str, List[str]]]=None,
    num_inference_steps: int=100, guidance_scale: float=4.0,
    num_images_per_prompt: int=1, height: int=512, width: int=512,
    prior_guidance_scale: float=4.0, prior_num_inference_steps: int=25,
    generator: Optional[Union[torch.Generator, List[torch.Generator]]]=None,
    latents: Optional[torch.Tensor]=None, output_type: Optional[str]='pil',
    callback: Optional[Callable[[int, int, torch.Tensor], None]]=None,
    callback_steps: int=1, return_dict: bool=True):
    """
        Function invoked when calling the pipeline for generation.

        Args:
            prompt (`str` or `List[str]`):
                The prompt or prompts to guide the image generation.
            image (`torch.Tensor`, `PIL.Image.Image`, `np.ndarray`, `List[torch.Tensor]`, `List[PIL.Image.Image]`, or `List[np.ndarray]`):
                `Image`, or tensor representing an image batch, that will be used as the starting point for the
                process. Can also accept image latents as `image`, if passing latents directly, it will not be encoded
                again.
            mask_image (`np.array`):
                Tensor representing an image batch, to mask `image`. White pixels in the mask will be repainted, while
                black pixels will be preserved. If `mask_image` is a PIL image, it will be converted to a single
                channel (luminance) before use. If it's a tensor, it should contain one color channel (L) instead of 3,
                so the expected shape would be `(B, H, W, 1)`.
            negative_prompt (`str` or `List[str]`, *optional*):
                The prompt or prompts not to guide the image generation. Ignored when not using guidance (i.e., ignored
                if `guidance_scale` is less than `1`).
            num_images_per_prompt (`int`, *optional*, defaults to 1):
                The number of images to generate per prompt.
            num_inference_steps (`int`, *optional*, defaults to 100):
                The number of denoising steps. More denoising steps usually lead to a higher quality image at the
                expense of slower inference.
            height (`int`, *optional*, defaults to 512):
                The height in pixels of the generated image.
            width (`int`, *optional*, defaults to 512):
                The width in pixels of the generated image.
            prior_guidance_scale (`float`, *optional*, defaults to 4.0):
                Guidance scale as defined in [Classifier-Free Diffusion Guidance](https://arxiv.org/abs/2207.12598).
                `guidance_scale` is defined as `w` of equation 2. of [Imagen
                Paper](https://arxiv.org/pdf/2205.11487.pdf). Guidance scale is enabled by setting `guidance_scale >
                1`. Higher guidance scale encourages to generate images that are closely linked to the text `prompt`,
                usually at the expense of lower image quality.
            prior_num_inference_steps (`int`, *optional*, defaults to 100):
                The number of denoising steps. More denoising steps usually lead to a higher quality image at the
                expense of slower inference.
            guidance_scale (`float`, *optional*, defaults to 4.0):
                Guidance scale as defined in [Classifier-Free Diffusion Guidance](https://arxiv.org/abs/2207.12598).
                `guidance_scale` is defined as `w` of equation 2. of [Imagen
                Paper](https://arxiv.org/pdf/2205.11487.pdf). Guidance scale is enabled by setting `guidance_scale >
                1`. Higher guidance scale encourages to generate images that are closely linked to the text `prompt`,
                usually at the expense of lower image quality.
            generator (`torch.Generator` or `List[torch.Generator]`, *optional*):
                One or a list of [torch generator(s)](https://pytorch.org/docs/stable/generated/torch.Generator.html)
                to make generation deterministic.
            latents (`torch.Tensor`, *optional*):
                Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
                generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
                tensor will ge generated by sampling using the supplied random `generator`.
            output_type (`str`, *optional*, defaults to `"pil"`):
                The output format of the generate image. Choose between: `"pil"` (`PIL.Image.Image`), `"np"`
                (`np.array`) or `"pt"` (`torch.Tensor`).
            callback (`Callable`, *optional*):
                A function that calls every `callback_steps` steps during inference. The function is called with the
                following arguments: `callback(step: int, timestep: int, latents: torch.Tensor)`.
            callback_steps (`int`, *optional*, defaults to 1):
                The frequency at which the `callback` function is called. If not specified, the callback is called at
                every step.
            return_dict (`bool`, *optional*, defaults to `True`):
                Whether or not to return a [`~pipelines.ImagePipelineOutput`] instead of a plain tuple.

        Examples:

        Returns:
            [`~pipelines.ImagePipelineOutput`] or `tuple`
        """
    prior_outputs = self.prior_pipe(prompt=prompt, negative_prompt=
        negative_prompt, num_images_per_prompt=num_images_per_prompt,
        num_inference_steps=prior_num_inference_steps, generator=generator,
        latents=latents, guidance_scale=prior_guidance_scale, output_type=
        'pt', return_dict=False)
    image_embeds = prior_outputs[0]
    negative_image_embeds = prior_outputs[1]
    prompt = [prompt] if not isinstance(prompt, (list, tuple)) else prompt
    image = [image] if isinstance(prompt, PIL.Image.Image) else image
    mask_image = [mask_image] if isinstance(mask_image, PIL.Image.Image
        ) else mask_image
    if len(prompt) < image_embeds.shape[0] and image_embeds.shape[0] % len(
        prompt) == 0:
        prompt = image_embeds.shape[0] // len(prompt) * prompt
    if isinstance(image, (list, tuple)) and len(image) < image_embeds.shape[0
        ] and image_embeds.shape[0] % len(image) == 0:
        image = image_embeds.shape[0] // len(image) * image
    if isinstance(mask_image, (list, tuple)) and len(mask_image
        ) < image_embeds.shape[0] and image_embeds.shape[0] % len(mask_image
        ) == 0:
        mask_image = image_embeds.shape[0] // len(mask_image) * mask_image
    outputs = self.decoder_pipe(prompt=prompt, image=image, mask_image=
        mask_image, image_embeds=image_embeds, negative_image_embeds=
        negative_image_embeds, width=width, height=height,
        num_inference_steps=num_inference_steps, generator=generator,
        guidance_scale=guidance_scale, output_type=output_type, callback=
        callback, callback_steps=callback_steps, return_dict=return_dict)
    self.maybe_free_model_hooks()
    return outputs
