@torch.no_grad()
def __call__(self, prompt: Union[str, List[str]], image: Union[torch.
    FloatTensor, PIL.Image.Image, List[PIL.Image.Image]],
    num_inference_steps: int=75, guidance_scale: float=9.0, negative_prompt:
    Optional[Union[str, List[str]]]=None, generator: Optional[Union[torch.
    Generator, List[torch.Generator]]]=None, latents: Optional[torch.
    FloatTensor]=None, output_type: Optional[str]='pil', return_dict: bool=
    True, callback: Optional[Callable[[int, int, torch.FloatTensor], None]]
    =None, callback_steps: int=1):
    """
        Function invoked when calling the pipeline for generation.

        Args:
            prompt (`str` or `List[str]`):
                The prompt or prompts to guide the image upscaling.
            image (`PIL.Image.Image` or List[`PIL.Image.Image`] or `torch.FloatTensor`):
                `Image`, or tensor representing an image batch which will be upscaled. If it's a tensor, it can be
                either a latent output from a stable diffusion model, or an image tensor in the range `[-1, 1]`. It
                will be considered a `latent` if `image.shape[1]` is `4`; otherwise, it will be considered to be an
                image representation and encoded using this pipeline's `vae` encoder.
            num_inference_steps (`int`, *optional*, defaults to 50):
                The number of denoising steps. More denoising steps usually lead to a higher quality image at the
                expense of slower inference.
            guidance_scale (`float`, *optional*, defaults to 7.5):
                Guidance scale as defined in [Classifier-Free Diffusion Guidance](https://arxiv.org/abs/2207.12598).
                `guidance_scale` is defined as `w` of equation 2. of [Imagen
                Paper](https://arxiv.org/pdf/2205.11487.pdf). Guidance scale is enabled by setting `guidance_scale >
                1`. Higher guidance scale encourages to generate images that are closely linked to the text `prompt`,
                usually at the expense of lower image quality.
            negative_prompt (`str` or `List[str]`, *optional*):
                The prompt or prompts not to guide the image generation. Ignored when not using guidance (i.e., ignored
                if `guidance_scale` is less than `1`).
            eta (`float`, *optional*, defaults to 0.0):
                Corresponds to parameter eta (η) in the DDIM paper: https://arxiv.org/abs/2010.02502. Only applies to
                [`schedulers.DDIMScheduler`], will be ignored for others.
            generator (`torch.Generator`, *optional*):
                One or a list of [torch generator(s)](https://pytorch.org/docs/stable/generated/torch.Generator.html)
                to make generation deterministic.
            latents (`torch.FloatTensor`, *optional*):
                Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
                generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
                tensor will ge generated by sampling using the supplied random `generator`.
            output_type (`str`, *optional*, defaults to `"pil"`):
                The output format of the generate image. Choose between
                [PIL](https://pillow.readthedocs.io/en/stable/): `PIL.Image.Image` or `np.array`.
            return_dict (`bool`, *optional*, defaults to `True`):
                Whether or not to return a [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] instead of a
                plain tuple.
            callback (`Callable`, *optional*):
                A function that will be called every `callback_steps` steps during inference. The function will be
                called with the following arguments: `callback(step: int, timestep: int, latents: torch.FloatTensor)`.
            callback_steps (`int`, *optional*, defaults to 1):
                The frequency at which the `callback` function will be called. If not specified, the callback will be
                called at every step.

        Examples:
        ```py
        >>> from diffusers import StableDiffusionLatentUpscalePipeline, StableDiffusionPipeline
        >>> import torch


        >>> pipeline = StableDiffusionPipeline.from_pretrained(
        ...     "CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16
        ... )
        >>> pipeline.to("cuda")

        >>> model_id = "stabilityai/sd-x2-latent-upscaler"
        >>> upscaler = StableDiffusionLatentUpscalePipeline.from_pretrained(model_id, torch_dtype=torch.float16)
        >>> upscaler.to("cuda")

        >>> prompt = "a photo of an astronaut high resolution, unreal engine, ultra realistic"
        >>> generator = torch.manual_seed(33)

        >>> low_res_latents = pipeline(prompt, generator=generator, output_type="latent").images

        >>> with torch.no_grad():
        ...     image = pipeline.decode_latents(low_res_latents)
        >>> image = pipeline.numpy_to_pil(image)[0]

        >>> image.save("../images/a1.png")

        >>> upscaled_image = upscaler(
        ...     prompt=prompt,
        ...     image=low_res_latents,
        ...     num_inference_steps=20,
        ...     guidance_scale=0,
        ...     generator=generator,
        ... ).images[0]

        >>> upscaled_image.save("../images/a2.png")
        ```

        Returns:
            [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] or `tuple`:
            [`~pipelines.stable_diffusion.StableDiffusionPipelineOutput`] if `return_dict` is True, otherwise a `tuple.
            When returning a tuple, the first element is a list with the generated images, and the second element is a
            list of `bool`s denoting whether the corresponding generated image likely represents "not-safe-for-work"
            (nsfw) content, according to the `safety_checker`.
        """
    self.check_inputs(prompt, image, callback_steps)
    batch_size = 1 if isinstance(prompt, str) else len(prompt)
    device = self._execution_device
    do_classifier_free_guidance = guidance_scale > 1.0
    if guidance_scale == 0:
        prompt = [''] * batch_size
    text_embeddings, text_pooler_out = self._encode_prompt(prompt, device,
        do_classifier_free_guidance, negative_prompt)
    image = preprocess(image)
    image = image.to(dtype=text_embeddings.dtype, device=device)
    if image.shape[1] == 3:
        image = self.vae.encode(image).latent_dist.sample(
            ) * self.vae.config.scaling_factor
    self.scheduler.set_timesteps(num_inference_steps, device=device)
    timesteps = self.scheduler.timesteps
    batch_multiplier = 2 if do_classifier_free_guidance else 1
    image = image[None, :] if image.ndim == 3 else image
    image = torch.cat([image] * batch_multiplier)
    noise_level = torch.tensor([0.0], dtype=torch.float32, device=device)
    noise_level = torch.cat([noise_level] * image.shape[0])
    inv_noise_level = (noise_level ** 2 + 1) ** -0.5
    image_cond = F.interpolate(image, scale_factor=2, mode='nearest'
        ) * inv_noise_level[:, None, None, None]
    image_cond = image_cond.to(text_embeddings.dtype)
    noise_level_embed = torch.cat([torch.ones(text_pooler_out.shape[0], 64,
        dtype=text_pooler_out.dtype, device=device), torch.zeros(
        text_pooler_out.shape[0], 64, dtype=text_pooler_out.dtype, device=
        device)], dim=1)
    timestep_condition = torch.cat([noise_level_embed, text_pooler_out], dim=1)
    height, width = image.shape[2:]
    num_channels_latents = self.vae.config.latent_channels
    latents = self.prepare_latents(batch_size, num_channels_latents, height *
        2, width * 2, text_embeddings.dtype, device, generator, latents)
    num_channels_image = image.shape[1]
    if (num_channels_latents + num_channels_image != self.unet.config.
        in_channels):
        raise ValueError(
            f'Incorrect configuration settings! The config of `pipeline.unet`: {self.unet.config} expects {self.unet.config.in_channels} but received `num_channels_latents`: {num_channels_latents} + `num_channels_image`: {num_channels_image}  = {num_channels_latents + num_channels_image}. Please verify the config of `pipeline.unet` or your `image` input.'
            )
    num_warmup_steps = 0
    with self.progress_bar(total=num_inference_steps) as progress_bar:
        for i, t in enumerate(timesteps):
            sigma = self.scheduler.sigmas[i]
            latent_model_input = torch.cat([latents] * 2
                ) if do_classifier_free_guidance else latents
            scaled_model_input = self.scheduler.scale_model_input(
                latent_model_input, t)
            scaled_model_input = torch.cat([scaled_model_input, image_cond],
                dim=1)
            timestep = torch.log(sigma) * 0.25
            noise_pred = self.unet(scaled_model_input, timestep,
                encoder_hidden_states=text_embeddings, timestep_cond=
                timestep_condition).sample
            noise_pred = noise_pred[:, :-1]
            inv_sigma = 1 / (sigma ** 2 + 1)
            noise_pred = (inv_sigma * latent_model_input + self.scheduler.
                scale_model_input(sigma, t) * noise_pred)
            if do_classifier_free_guidance:
                noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                noise_pred = noise_pred_uncond + guidance_scale * (
                    noise_pred_text - noise_pred_uncond)
            latents = self.scheduler.step(noise_pred, t, latents).prev_sample
            if i == len(timesteps) - 1 or i + 1 > num_warmup_steps and (i + 1
                ) % self.scheduler.order == 0:
                progress_bar.update()
                if callback is not None and i % callback_steps == 0:
                    callback(i, t, latents)
    image = self.decode_latents(latents)
    if output_type == 'pil':
        image = self.numpy_to_pil(image)
    if not return_dict:
        return image,
    return ImagePipelineOutput(images=image)
