# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class OnnxStableDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod


class OnnxStableDiffusionInpaintPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod


class OnnxStableDiffusionInpaintPipelineLegacy(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod


class OnnxStableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod


class OnnxStableDiffusionUpscalePipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod


class StableDiffusionOnnxPipeline(metaclass=DummyObject):
    _backends = ["torch", "transformers", "onnx"]


    @classmethod

    @classmethod